webapp/client/__init__.py
from flask import Blueprint, current_app

client = Blueprint('client', __name__,
                   static_folder='static',
                   static_url_path='/static/client',
                   template_folder='templates')

from . import views

if current_app.config.get('DEBUG') and current_app.config.get('WEBSOCKETS_ENABLED'):
    from . import dev_websocket_views

if current_app.config.get('DEBUG') and current_app.config.get('WORKERS_ENABLED'):
    from . import dev_worker_views

webapp/client/views.py
from collections import OrderedDict, defaultdict

from flask import render_template, flash, redirect, request
from flask_security import login_required, roles_required

from webapp.client import client
from webapp.api.models import BlogPost


class OrderedDefaultDict(OrderedDict, defaultdict):
    def __init__(self, default_factory=None, *args, **kwargs):
        super(OrderedDefaultDict, self).__init__(*args, **kwargs)
        self.default_factory = default_factory


@client.route('/')
def get_blog():
    blog_posts = BlogPost.get_all_by(order_by=BlogPost.created_ts.desc())
    dated_bp = OrderedDefaultDict(list)
    for bp in blog_posts:
        dated_bp[bp.created_ts.date()].append(bp)
    return render_template('index.html',
                           dated_bp=dated_bp,
                           title="PiSquared Blog")


@client.route('/projects')
def get_projects():
    return render_template('projects.html',
                           title="PiSquared Projects")

@client.route('/about_me')
def get_aboutme():
    return render_template('aboutme.html',
                           title="PiSquared About Me")


@client.route('/blog_posts/new')
@login_required
@roles_required('admin',)
def get_blog_posts_new():
    return render_template('blog_posts_new.html',
                           title="PiSquared Projects")


@client.route('/blog_posts/<int:instance_id>/edit')
@login_required
@roles_required('admin', )
def get_blog_posts_edit(instance_id):
    bp = BlogPost.get_one_by(id=instance_id)
    if not bp:
        flash('No BlogPost with id {}'.format(instance_id))
        return redirect(request.referrer)
    return render_template('blog_posts_edit.html',
                           title="PiSquared Projects",
                           bp=bp)

webapp/client/templates/aboutme.html
{% extends "layout_main.html" %}
{% import "_macros.html" as macros %}

{% block style %}
    {{ macros.include_css('index') }}
{% endblock %}

{% block content %}
<table style="border: 0px;"><tbody>
<tr>
<td style="padding: 26px;"><h1>
Pi Squared&nbsp;<span style="background-color: white; font-family: serif; font-size: 36.7999992370606px; font-weight: normal;">⇔</span>&nbsp;Daniel Tsvetkov</h1>
<div style="text-align: justify; vertical-align: top;">
Hi.<br />
<br />
I do computer stuff, run, and run side projects about computer stuff. <br />
<br />
I enjoy physics, astronomy, science in general. I like to go to competitions and hackathons of various sorts, meet interesting people, exchange crazy ideas and meet again one day somewhere in the world (happens all the time). I have many ideas, theories and views about the world and that's why I have this blog.<br />
<br /></div>
<div style="text-align: justify;">
<a href="http://pi2squared.blogspot.co.uk/" style="clear: right; float: right; margin-bottom: 1em; margin-left: 1em;" target="_blank"><img alt="Pi2 Logo" src="https://lh4.googleusercontent.com/-ACTswkUyoHM/UK1w-iM4uaI/AAAAAAAA76E/nr7NHzJiOH0/s616/373962_2733853193004_528596565_n.jpg" width="126" /></a><br />
Pi Squared because when I was small I loved reading <a href="http://www.murderousmaths.co.uk/" target="_blank">Murderous Maths</a> books. In one of them, they explained how&nbsp;<span style="background-color: white; color: #545454; font-family: &quot;arial&quot; , sans-serif; font-size: x-small; line-height: 18.2000007629395px; text-align: left;">π</span><span style="background-color: #f9f9f9; font-family: sans-serif; font-size: 14px; line-height: 22.3999996185303px;">²</span>&nbsp;it is not frequently met in formulas and since then I am a fan.<br />
<br />
I write some of my posts in Bulgarian because sometimes I need to express my frustrations in my own language.<br />
<br />
<a href="https://gitlab.com/pisquared" target="_blank"><i class="fa fa-gitlab"></i> GitLab</a> |
    <a href="https://www.linkedin.com/in/danieltsvetkov" target="_blank"><i class="fa fa-linkedin"></i> LinkedIn</a></div>

</td><td style="vertical-align: top;">&nbsp; &nbsp;&nbsp;&nbsp;</td></tr>
<tr><td colspan="2"><br />
<h2 style="background-color: #333333; color: #cccccc; font-size: 22px; padding: 5px;">
Opinew<span style="float: right;">Glasgow</span></h2>
<div style="background-color: #888888; color: #dddddd; font-size: 16px; padding: 3px;">
November 2014 - December 2016 <span style="float: right;">Start up founder</span></div>
<div style="background-color: #dddddd; padding: 10px; text-align: justify;">
<div style="height: 226px; overflow: hidden;">
<img alt="Opinew Logo" src="https://lh5.googleusercontent.com/-JrGUoJa9ytg/VO-QvGyx2wI/AAAAAAABixo/QKaxSMl4GVE/w1044-h499-no/opinew_black.png" style="margin-top: -50px;" width="600" /></div>
<br />
<a href="http://www.opinew.com/">Opinew</a> - find and express opinions about anything! Creating a service that aggregates opinions about everything. A single place where you can search opinions, express your beliefs about the topics you care the most and be recognized as an expert by the community.
</div>
<br />
<h2 style="background-color: #333333; color: #cccccc; font-size: 22px; padding: 5px;">
Google Internship<span style="float: right;">Mountain View</span></h2>
<div style="background-color: #888888; color: #dddddd; font-size: 16px; padding: 3px;">
June 2014 - September 2014<span style="float: right;">Internship</span></div>
<div style="background-color: #dddddd; padding: 10px; text-align: justify;">
<div style="height: 226px; overflow: hidden;">
<img alt="Google Intern" src="https://lh3.googleusercontent.com/-IMIlTRlur0E/VO-PAm4RvQI/AAAAAAABixU/NWe3s5FdgSI/w439-h234-no/gi.png" style="margin-top: -50px;" width="600" /></div>
<br />
Internship at Google in the heart of the Silicon Valley - Mountain View. Working on infrastructure project, creating visualizations and summary reports. Other than that - played a lot of quidditch, visited Disneyland and got to know amazing people.</div>
<br />
<h2 style="background-color: #333333; color: #cccccc; font-size: 22px; padding: 5px;">
Glasgow University Tech Society<span style="float: right;">Glasgow</span></h2>
<div style="background-color: #888888; color: #dddddd; font-size: 16px; padding: 3px;">
September 2013 - November 2014<span style="float: right;">Internship</span></div>
<div style="background-color: #dddddd; padding: 10px; text-align: justify;">
<div style="height: 226px; overflow: hidden;">
<img alt="Google Intern" src="https://lh4.googleusercontent.com/-4Obgf-PPgiM/VO-Sxx8GhGI/AAAAAAABix0/G25ok9jnvvE/w840-h345-no/guts.JPG" style="margin-top: -50px;" width="600" /></div>
Organizing events, workshops and groups with extra curricular activities to give the competitive advantage of University of Glasgow students in IT industry. Created the <a href="http://gutechsoc.com/" target="_blank">webpage</a> of the society. Organized a two 48 hour <a href="http://gutechsoc.com/hackathon" target="_blank">hackathon events</a> with financial support of Skyscanner, SAS, Github, Barclays, JPMorgan, Dominos, SIE, Informatic ventures and others.</div>
<br />
<h2 style="background-color: #333333; color: #cccccc; font-size: 22px; padding: 5px;">
JPMorgan Code for Good<span style="float: right;">London</span></h2>
<div style="background-color: #888888; color: #dddddd; font-size: 16px; padding: 3px;">
16 - 18 November 2012 <span style="float: right;">Competition</span></div>
<div style="background-color: #dddddd; padding: 10px; text-align: justify;">
<div style="height: 226px; overflow: hidden;">
<img alt="JPMorgan Code for good" src="https://lh5.googleusercontent.com/-oKbCXm9Tc0c/UK10s_xA51I/AAAAAAAA76U/xkdg2ZegsdI/s720/NPMG.jpg" style="margin-top: -50px;" width="600" /></div>
<br />
A hackaton-style competition called <a href="http://techcareers.jpmorgan.com/opportunities/codeforgood.aspx" target="_blank">J.P. Morgan Code for Good</a>. Together with a team (from my old school) we had to code an application for <a href="http://www.nature.org/" target="_blank">Nature Conservacy</a> in about 24 hours from scratch. Our idea was to create a web app where everyone can take  challenges to help the environment - alone or with friends. The code for the application is public in a <a href="http://github.com/danieltcv/JPMorganOfficial" target="_blank">github repo</a>.
</div>
<br />
<h2 style="background-color: #333333; color: #cccccc; font-size: 22px; padding: 5px;">
Google Android Camp <span style="float: right;">London</span></h2>
<div style="background-color: #888888; color: #dddddd; font-size: 16px; padding: 3px;">
12 - 18 August 2012 <span style="float: right;">Camp</span></div>
<div style="background-color: #dddddd; padding: 10px; text-align: justify;">
<div style="height: 226px; overflow: hidden;">
<img alt="Google Android Camp" src="https://lh6.googleusercontent.com/-Bqk8Te13QkA/UK15Tf7LRNI/AAAAAAAA76g/zCaDhVxx90c/s725/556437_307464292684136_1520730880_n.jpg" style="margin-top: -50px;" width="600" /></div>
<br />
My first London visit was accompanied by incredible journey through Google offices, a LOT of coding while learning the Android platform, lots of food and amazing people. That's what <a href="http://googleforstudents.blogspot.co.uk/2012/10/google-android-camp-comes-to-london.html" target="_blank">Google Android Camp</a> was about. Oh, and my team (called "Random" bizarrely, the name was not even chosen by me!) won first place. We made an application for cooking with recepies but with the subtle difference that it dictates the recipes and you can voice control it (sort of).
</div>
<br />
<h2 style="background-color: #333333; color: #cccccc; font-size: 22px; padding: 5px;">
Физици Филми ("Physicists Films") <span style="float: right;"></span></h2>
<div style="background-color: #888888; color: #dddddd; font-size: 16px; padding: 3px;">
2007 - 2012 <span style="float: right;">Project</span></div>
<div style="background-color: #dddddd; padding: 10px; text-align: justify;">
<div style="height: 226px; overflow: hidden;">
<img alt="Physicist Films project" src="https://lh5.googleusercontent.com/-9pqihy7_YVM/Thg0oOyk9iI/AAAAAAAAmyY/t6cG_LJq_fI/s720/IMG_2036.JPG" style="margin-top: -50px;" width="600" /></div>
<br />
During high school together with my classmate Alexander Lalev we made documentary movies about physics and we called our project <a href="http://fizicifilms.host56.com/" target="_blank">"Physicists Films"</a>. It demonstrated science as we saw it, outside of the classroom boundaries. The films were uploaded by us for <a href="http://www.youtube.com/playlist?list=PLkPqEDagL5wRGtni0FOTCGB3uPLPUXA83">free</a> as we believe that knowledge must be free and everyone should benefit from it. We presented the movies in schools, conferences and competitions, most notably the <a href="http://ese2010.ru/" target="_blank">Euro-Expo Sciences 2010</a> in Moscow. It surely was great fun and we are looking forward to continue our project one day.
</div>
<br />
<h2 style="background-color: #333333; color: #cccccc; font-size: 22px; padding: 5px;">
International Astronomy Olympiad <span style="float: right;">Crimea</span></h2>
<div style="background-color: #888888; color: #dddddd; font-size: 16px; padding: 3px;">
29 October - 14 November 2007 <span style="float: right;">Competition</span></div>
<div style="background-color: #dddddd; padding: 10px; text-align: justify;">
<div style="height: 226px; overflow: hidden;">
<img alt="International Astronomy Olympiad 2007" src="https://lh3.googleusercontent.com/-OmcqhbnocBE/Tg0SQQeozyI/AAAAAAAApcw/7d_F4geA_2I/s640/IAO_%25252520%25252528132%25252529.jpg" style="margin-top: -100px;" width="600" /><span style="float: right;">Crimea</span></div>
<br />
Amazing journey to Crimea peninsula where the XIIIth <a href="http://www.issp.ac.ru/iao/" target="_blank">International Astronomy Olympiad</a> was held. We traveled by train for three days where we were solving problems, getting to know each other quite close (ha-ha) and enjoy big walks in Kiev. The nature in Crimea was astonishing just in the middle of the autumn and the competition was quite fierce. However we god one first place, one second and two bronze.
</div>
<br /></td></tr>
</tbody></table>

{% endblock %}

{% block script %}
{% endblock %}

webapp/client/templates/blog_posts_edit.html
{% extends "layout_main.html" %}
{% import "_macros.html" as macros %}

{% block style %}
    {{ macros.include_css('index') }}
{% endblock %}

{% block content %}
    <form action="{{ url_for('api.blog_post_update_nojs', instance_id=bp.id) }}" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="hidden" name="next" value="/"/>
        <div class="form-group">
            <label for="journal-entry">Blog Post: </label>
            <textarea id="journal-entry" name="body" rows="12" class="form-control">{{ bp.body }}</textarea>
        </div>
        <button class="btn btn-primary">Update</button>
    </form>
{% endblock %}

{% block script %}
    {{ macros.include_js('index') }}
{% endblock %}

webapp/client/templates/blog_posts_new.html
{% extends "layout_main.html" %}
{% import "_macros.html" as macros %}

{% block style %}
    {{ macros.include_css('index') }}
{% endblock %}

{% block content %}
    <form action="{{ url_for('api.blog_post_create_nojs') }}" method="post">
        <input type="hidden" name="csrf_token" value="{{ csrf_token() }}"/>
        <input type="hidden" name="next" value="/"/>
        <div class="form-group">
            <label for="journal-entry">Blog Post: </label>
            <textarea id="journal-entry" name="body" rows="12" class="form-control"></textarea>
        </div>
        <button class="btn btn-primary">Create</button>
    </form>
{% endblock %}

{% block script %}
    {{ macros.include_js('index') }}
{% endblock %}

webapp/client/templates/favicons.html
<link rel="apple-touch-icon" sizes="57x57" href="{{ url_for('static', filename='client/img/favicons/apple-icon-57x57.png')}}">
<link rel="apple-touch-icon" sizes="60x60" href="{{ url_for('static', filename='client/img/favicons/apple-icon-60x60.png')}}">
<link rel="apple-touch-icon" sizes="72x72" href="{{ url_for('static', filename='client/img/favicons/apple-icon-72x72.png')}}">
<link rel="apple-touch-icon" sizes="76x76" href="{{ url_for('static', filename='client/img/favicons/apple-icon-76x76.png')}}">
<link rel="apple-touch-icon" sizes="114x114" href="{{ url_for('static', filename='client/img/favicons/apple-icon-114x114.png')}}">
<link rel="apple-touch-icon" sizes="120x120" href="{{ url_for('static', filename='client/img/favicons/apple-icon-120x120.png')}}">
<link rel="apple-touch-icon" sizes="144x144" href="{{ url_for('static', filename='client/img/favicons/apple-icon-144x144.png')}}">
<link rel="apple-touch-icon" sizes="152x152" href="{{ url_for('static', filename='client/img/favicons/apple-icon-152x152.png')}}">
<link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='client/img/favicons/apple-icon-180x180.png')}}">
<link rel="icon" type="image/png" sizes="192x192"  href="{{ url_for('static', filename='client/img/favicons/android-icon-192x192.png')}}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='client/img/favicons/favicon-32x32.png')}}">
<link rel="icon" type="image/png" sizes="96x96" href="{{ url_for('static', filename='client/img/favicons/favicon-96x96.png')}}">
<link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='client/img/favicons/favicon-16x16.png')}}">
<link rel="manifest" href="{{ url_for('static', filename='client/img/favicons/manifest.json')}}">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">

webapp/client/templates/index.html
{% extends "layout_main.html" %}
{% import "_macros.html" as macros %}

{% block style %}
    {{ macros.include_css('index') }}
{% endblock %}

{% block content %}
    {% for dt, bps in dated_bp.iteritems() %}
        {% for bp in bps %}
            {% if current_user.has_role('admin') %}
                <a href="{{ url_for('client.get_blog_posts_edit', instance_id=bp.id) }}">edit</a>
                <a href="{{ url_for('api.blog_post_delete_nojs', instance_id=bp.id) }}" class="text-danger">delete</a>
            {% endif %}
            <blockquote class="blockquote">
                <footer class="blockquote-footer pull-right">
                    <cite>{{ bp.created_ts|format_dt("%A, %d %B, %H:%M") }}</cite>
                </footer>
                <p>{{ bp.body|markdown }}</p>
            </blockquote>
            <hr>
        {% endfor %}
    {% endfor %}
{% endblock %}

{% block script %}
    {{ macros.include_js('index') }}
{% endblock %}

webapp/client/templates/layout_main.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{% if current_user.is_authenticated and current_user.has_role('admin') %}[ADMIN] {% endif %}{{ title or "App" }}</title>
    {% include "favicons.html" %}
    {% import "_macros.html" as macros %}
    {{ macros.include_css('layout') }}
    {% block style %}{% endblock %}
</head>
<body>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{% if category == 'message' %}danger{% else %}{{ category }}{% endif %}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
{% endwith %}
<div class="container">
    {% include "navigation.html" %}
    {% block content %}{% endblock %}
</div>

<script>
  var DEBUG = {% if config.DEBUG %}true{% else %}false{% endif %}
</script>
{{ macros.include_js('layout') }}
{% block script %}{% endblock %}
</body>
</html>

webapp/client/templates/navigation.html
<div class="row">
    <div class="col-12">
        <ul class="nav">
            {% if current_user.is_authenticated and current_user.has_role('admin') %}
                <li class="nav-item">
                    <a class="nav-link text-danger" href="{{ url_for('client.get_blog_posts_new') }}">Write</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-danger" href="{{ url_for('security.logout') }}">Log Out</a>
                </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link active" href="{{ url_for('client.get_blog') }}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('client.get_projects') }}">Projects</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('client.get_aboutme') }}">About Me</a>
            </li>
        </ul>
    </div>
</div>

webapp/client/templates/projects.html
{% extends "layout_main.html" %}
{% import "_macros.html" as macros %}

{% block style %}
    {{ macros.include_css('index') }}
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">Prodday</h5>
                    <p class="card-text">All your productivity needs in one place.</p>
                    <a href="https://gitlab.com/pisquared/prodday" target="_blank" class="btn btn-default"><i class="fa fa-gitlab"></i> Code</a>
                    <a href="https://prodday.com/" target="_blank" class="btn btn-primary"><i class="fa fa-calendar"></i> WebApp</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block script %}
    {{ macros.include_js('index') }}
{% endblock %}